
const data = {
    status: "success",
    items: [
        {
            id: 1,
            name: "teclados",
            image: require("../images/produtos/produto-teclado.png"),
            title: "TECLADO MECÂNICO REDRAGON",
            price: "274,99",
            pricenow: "204,99",
            description: "Switch Azul K606R (PT-BLUE) Preto",
            link: "produto-teclado-redragon",
            discount: "-25%",
            class: "teclado"
        },
        {
            id: 2,
            name: "mousepads",
            image: require("../images/produtos/Tokyo-Mouse-Pad.png"),
            title: "MOUSEPAD AKKO",
            price: "175,99",
            pricenow: "154,99",
            description: "World Tour Tokio R2",
            link: "mousepad-tokyo",
            discount: "-12%",
            class: "mousepad-tokyo"
        },
        {
            id: 3,
            name: "mousepads",
            image: require("../images/produtos/Tokyo-Mouse-Pad-Dracula.png"),
            title: "MOUSEPAD AKKO",
            price: "175,99",
            pricenow: "154,99",
            description: "Dracula Castle",
            link: "mousepad-dracula",
            discount: "-12%",
            class: "mousepad-dracula-london"
        },
        {
            id: 4,
            name: "mousepads",
            image: require("../images/produtos/Tokyo-Mouse-Pad-London.png"),
            title:"MOUSEPAD AKKO",
            price: "175,99",
            pricenow: "154,99",
            description: "World Tour London",
            link: "mousepad-london",
            discount: "-12%",
            class: "mousepad-dracula-london"
        },
        {
            id: 5,
            name: "cabo-teclado",
            image: require("../images/produtos/cabo-akko-blue.png"),
            title: "CABO TECLADO",
            price: "69,99",
            pricenow: "49,99",
            description: "Cabo Enrolado Modelo Blue",
            link: "keyboard-cable-blue",
            discount: "-28%",
            class: "cable-pink"
        },
        {
            id: 6,
            name: "cabo-teclado",
            image: require("../images/produtos/cabo-akko-pink.png"),
            title:"CABO TECLADO",
            price: "69,99",
            pricenow: "49,99",
            description:"Cabo Enrolado Modelo Pink",
            link: "keyboard-cable-blue",
            discount: "-28%",
            class: "cable-pink"
        },
        {
            id: 7,
            name: "teclados",
            image: require("../images/produtos/teclado-akko.jpg"),
            title:"TECLADO MECÂNICO AKKO",
            price: "726,90",
            pricenow: "599,99",
            description:"Switch Akko Pink World Tour Tokio R1",
            link: "produto-teclado-akko",
            discount: "-17%",
            class: "teclado"
        },
        {
            id: 8,
            name: "headsets",
            image: require("../images/produtos/headset-hebe.png"),
            title: "HEADSET GAMER",
            price: "179,99",
            pricenow: "159,99",
            description: "Headset Gamer Hebe E2",
            link: "headset-hebe",
            discount: "-11%",
            class: "headset"
        },
        {
            id: 9,
            name: "headsets",
            description: "Headset Scylla Preto H901",
            image: require("../images/produtos/headset-scylla-preto.png"),
            price: "149,99",
            pricenow: "119,99",
            discount: "-20%",
            title: "HEADSET GAMER",
            link: "headset-scylla",
            class: "headset"
        },
        {
            id: 10,
            name: "headsets",
            description: "Headset Minos Preto H210",
            image: require("../images/produtos/headset-minos-preto.png"),
            price: "199,99",
            pricenow: "179,99",
            discount: "-10%",
            title: "HEADSET GAMER",
            link: "headset-minos",
            class: "headset"
        },
        {
            id: 11,
            name: "headsets",
            image: require("../images/produtos/Hylas.png"),
            title: "HEADSET GAMER",
            price: "149,99",
            pricenow: "124,99",
            description: "Headset Hylas Rosa H260-P",
            link: "headset-hylas",
            discount: "-16%",
            class: "headset"
        },
        {
            id: 12,
            name: "headsets",
            image: require("../images/produtos/headset-taurus.png"),
            title: "HEADSET GAMER",
            price: "99,99",
            pricenow: "79,99",
            description: "Headset Taurus E1",
            link: "headset-taurus",
            discount: "-20%",
            class: "headset"
        },
        {
            id: 13,
            name: "headsets",
            image: require("../images/produtos/hero-branco.webp"),
            title:"HEADSET GAMER",
            price: "299,99",
            pricenow: "269,99",
            description: "Headset Hero Branco H530",
            link: "headset-hero",
            discount: "-12%",
            class: "headset"
        },
        {
            id: 14,
            name: "gabinetes",
            image: require("../images/produtos/gabinete-g25b.png"),
            title: "GABINETE GAMER",
            price: "249,99",
            pricenow: "219,99",
            description: "Gabinete T-DAGGER TGC-G25B Preto",
            link: "gabinete-gamer-g25b",
            discount: "-12%",
            class: "gabinete"
        },
        {
            id: 15,
            name: "gabinetes",
            image: require("../images/produtos/gabinete-g28b.png"),
            title: "GABINETE GAMER",
            price: "249,99",
            pricenow: "219,99",
            description: "Gabinete T-DAGGER TGC-G28B Preto",
            link: "gabinete-gamer-g28b",
            discount: "-12%",
            class: "gabinete"
        },
        {
            id: 16,
            name: "mouses",
            image: require("../images/produtos/mouse_reaping.png"),
            title: "MOUSE GAMER",
            price: "239,99",
            pricenow: "209,99",
            description: "Mouse Readragon Reaping Elite Preto",
            link: "mouse-reaping",
            discount: "-13%",
            class: "mouse-reaping"
        },
        {
            id: 17,
            name: "mouses",
            image: require("../images/produtos/mouse_gamer_rmouse_storm.png"),
            title: "MOUSE GAMER",
            price: "219,99",
            pricenow: "194,99",
            description: "Mouse Redragon Storm Elite",
            link: "mouse-storm",
            discount: "-11%",
            class: "mouses"
        },
        {
            id: 18,
            name: "mouses",
            image: require("../images/produtos/mouse_imperial.webp"),
            title: "MOUSE GAMER",
            price: "139,99",
            pricenow: "109,99",
            description: "Mouse Imperial T-DAGGER Preto",
            link: "mouse-imperial",
            discount: "-21%",
            class: "mouses"
        },
        {
            id: 19,
            name: "mouses",
            image: require("../images/produtos/mouse-redragon-cobra-preto.webp"),
            title: "MOUSE GAMER",
            price: "139,99",
            pricenow: "124,99",
            description: "Mouse Redragon Cobra M711",
            link: "mouse-cobra-preto",
            discount: "-11%",
            class: "mouses"
        },
        {
            id: 20,
            name: "mouses",
            image: require("../images/produtos/mouse-cobra-branco.png"),
            title: "MOUSE GAMER",
            price: "209,99",
            pricenow: "194,99",
            description: "Mouse Redragon Cobra FPS M711W",
            link: "mouse-cobra-fps-branco",
            discount: "-8%",
            class: "mouses"
        },
        {
            id: 21,
            name: "mouses",
            image: require("../images/produtos/Mouse-redragon-cobra-FPS.png"),
            title: "MOUSE GAMER",
            price: "219,99",
            pricenow: "194,99",
            description: "Mouse Redragon Cobra FPS Preto M711B",
            link: "mouse-cobra-fps-preto",
            discount: "-10%",
            class: "mouse-reaping"
        },
        {
            id: 22,
            name: "mousepads",
            image: require("../images/produtos/mousepad-kunlun.png"),
            title: "MOUSEPAD REDRAGON",
            price: "119,99",
            pricenow: "89,99",
            description: "Mousepad Redragon Kunlun EXT Preto",
            link: "mousepad-kunlun",
            discount: "-25%",
            class: "mousepad-new"
        },
        {
            id: 23,
            name: "mousepads",
            image: require("../images/produtos/mousepad-redragon-flick.png"),
            title: "MOUSEPAD REDRAGON",
            price: "99,99",
            pricenow: "79,99",
            description: "Mousepad Redragon Flick L Preto",
            link: "mousepad-flick",
            discount: "-20%",
            class: "mousepad-flick"
        },
        {
            id: 24,
            name: "teclados",
            image: require("../images/produtos/dar-avenger-rainbow.png"),
            title: "TECLADO MECÂNICO REDRAGON",
            price: "249,99",
            pricenow: "209,99",
            description: "Dark Avenger Rainbow - Switch Blue",
            link: "teclado-dark-switch-blue",
            discount: "-16%",
            class: "teclado-double-switch"
        },
        {
            id: 25,
            name: "teclados",
            image: require("../images/produtos/teclado-mecanico-redragon-white.png"),
            title: "TECLADO MECÂNICO REDRAGON",
            price: "269,99",
            pricenow: "209,99",
            description: "Dark Avenger Rainbow Lunar White",
            link: "teclado-dark-white",
            discount: "-22%",
            class: "teclado-white"
        },
        {
            id: 26,
            name: "mouses",
            image: require("../images/produtos/mouse-storm-lunar.webp"),
            title: "MOUSE GAMER",
            price: "189,99",
            pricenow: "159,99",
            description: "Mouse Storm RGB Lunar White",
            link: "mouse-storm-lunar",
            discount: "-15%",
            class: "mouses"
        },
        {
            id: 27,
            name: "mousepads",
            image: require("../images/produtos/mousepad-redragon-taurus.webp"),
            title: "MOUSEPAD REDRAGON",
            price: "89,99",
            pricenow: "64,99",
            description: "Mousepad EXT Taurus Speed",
            link: "mousepad-taurus",
            discount: "-27%",
            class: "mousepad-tokyo"
        },
        {
            id: 28,
            name: "teclados",
            image: require("../images/produtos/teclado-dark-260.png"),
            title: "TECLADO MECÂNICO REDRAGON",
            price: "299,99",
            pricenow: "259,99",
            description: "Dark Avenger RGB - Switch Red",
            link: "teclado-dark-switch-red",
            discount: "-13%",
            class: "teclado-double-switch"
        },
        {
            id: 29,
            name: "kits",
            image: require("../images/produtos/mousepad-mouse.png"),
            title: "KIT MOUSE E MOUSEPAD REDRAGON",
            price: "189,99",
            pricenow: "159,99",
            description: "M607-BA Kit mouse e mousepad P003",
            link: "kit-mouse-pad",
            discount: "-15%",
            class: "kit-mouse-pad"
        },
        {
            id: 30,
            name: "kits",
            image: require("../images/produtos/keycaps-a107.png"),
            title: "KIT KEYCAPS REDRAGON PRETO",
            price: "99,99",
            pricenow: "64,99",
            description: "Kit Completo de Teclas Redragon Preto - A107",
            link: "keycaps-a107",
            discount: "-35%",
            class: "keycaps"
        },
        {
            id: 31,
            name: "kits",
            image: require("../images/produtos/keycaps-a130.png"),
            title: "KIT KEYCAPS REDRAGON SCARAB",
            price: "89,99",
            pricenow: "71,50",
            description: "Kit Completo de Teclas Redragon Scarab - A130",
            link: "keycaps-a130",
            discount: "-20%",
            class: "keycaps"
        },
        {
            id: 32,
            name: "switches",
            image: require("../images/produtos/kit-tactile.png"),
            title: "KIT SWITCH REDRAGON TACTILE",
            price: "89,99",
            pricenow: "71,50",
            description: "Switch Para Teclado Mecânico - A113B",
            link: "switch-redragon",
            discount: "-20%",
            class: "kit-mouse-pad"
        },
        {
            id: 33,
            name: "soundbar",
            image: require("../images/produtos/sound-bar.png"),
            title: "SOUNDBAR REDRAGON ADIEMUS",
            price: "149,99",
            pricenow: "129,99",
            description: "Caixa de Som Soundbar - GS560",
            link: "soundbar",
            discount: "-13%",
            class: "soundbar"
        },
        {
            id: 34,
            name: "teclados",
            image: require("../images/produtos/gamdias-02.png"),
            title: "TECLADO GAMER HERMES E2",
            price: "199,99",
            pricenow: "159,99",
            description: "Teclado Gamer Gamdias Hermes E2 - Switch Blue",
            link: "gamdias-e2",
            discount: "-20%",
            class: "teclado"
        },
        {
            id: 35,
            name: "teclados",
            image: require("../images/produtos/gamdias-03.png"),
            title: "TECLADO GAMER HERMES E3",
            price: "399,99",
            pricenow: "349,99",
            description: "Teclado Gamer Gamdias Hermes E3 - Switch Brown",
            link: "gamdias-e3",
            discount: "-12%",
            class: "teclado-gamdias"
        },
        {
            id: 36,
            name: "headsets",
            image: require("../images/produtos/headset-hyperx.png"),
            title: "HEADSET GAMER",
            price: "209,99",
            pricenow: "169,99",
            description: "Headset HyperX Cloud Stinger Core",
            link: "headset-hyperx",
            discount: "-19%",
            class: "headset"
        },
        {
            id: 37,
            name: "headsets",
            image: require("../images/produtos/headphone-motorola.png"),
            title: "HEADPHONE MOTOROLA",
            price: "149,99",
            pricenow: "109,99",
            description: "Headphone Motorola Pulse 120",
            link: "headphone-motorola",
            discount: "-26%",
            class: "headset-motorola"
        },
        {
            id: 38,
            name: "teclados",
            image: require("../images/produtos/teclado-bora.png"),
            title: "TECLADO GAMER TDAGGER",
            price: "279,99",
            pricenow: "229,99",
            description: "Teclado Gamer TDAGGER Bora RGB",
            link: "teclado-tdagger-bora",
            discount: "-17%",
            class: "teclado-gamdias"
        },
        {
            id: 40,
            name: "headsets",
            image: require("../images/produtos/hero-branco-vermelho.webp"),
            title: "HEADSET GAMER",
            price: "299,99",
            pricenow: "269,99",
            description: "Headset Hero Branco com Vermelho H530-WP",
            link: "headset-hero-branco-vermelho",
            discount: "-12%",
            class: "headset-hero"
        },
        {
            id: 41,
            name: "kits",
            image: require("../images/produtos/keycap-oem.png"),
            title: "KIT KEYCAPS AKKO RETRO",
            price: "69,99",
            pricenow: "49,99",
            description: "Keycaps Profile OEM Retro R2 (38-Key)",
            link: "keycaps-akko-retro",
            discount: "-28%",
            class: "kit-mouse-pad"
        },
        {
            id: 42,
            name: "teclados",
            image: require("../images/produtos/akko-jelly-pink.jpg"),
            title: "TECLADO MECÂNICO AKKO 3068 V2",
            price: "529,99",
            pricenow: "499,99",
            description: "Switch Jelly Pink - 65% RGB White",
            link: "teclado-akko-jelly-white",
            discount: "-5%",
            class: "teclado-jelly"
        },
        {
            id: 43,
            name: "teclados",
            image: require("../images/produtos/akko-jelly-black.jpg"),
            title: "TECLADO MECÂNICO AKKO 3068 V2",
            price: "529,99",
            pricenow: "499,99",
            description: "Switch Jelly Pink - 65% RGB Black",
            link: "teclado-akko-jelly-black",
            discount: "-5%",
            class: "teclado-jelly"
        },
        {
            id: 44,
            name: "switches",
            image: require("../images/produtos/switch-rose-red.png"),
            title: "KIT SWITCH AKKO ROSE RED",
            price: "89,99",
            pricenow: "71,99",
            description: "Switch Para Teclado Mecânico Akko.",
            link: "switch-akko-rose-red",
            discount: "-20%",
            class: "switches"
        },
        {
            id: 45,
            name: "switches",
            image: require("../images/produtos/switch-matcha.png"),
            title: "KIT SWITCH AKKO MATCHA GREEN",
            price: "89,99",
            pricenow: "71,99",
            description: "Switch Para Teclado Mecânico Akko.",
            link: "switch-akko-matcha-green",
            discount: "-20%",
            class: "switches"
        },
        {
            id: 46,
            name: "switches",
            image: require("../images/produtos/switch-vintage.png"),
            title: "KIT SWITCH AKKO VINTAGE WHITE",
            price: "85,99",
            pricenow: "74,99",
            description: "Switch Para Teclado Mecânico Akko.",
            link: "switch-akko-vintage-white",
            discount: "-12%",
            class: "switches"
        },
        {
            id: 47,
            name: "cabo-teclado",
            image: require("../images/produtos/cabo-black-pink.png"),
            title: "CABO PARA TECLADO",
            price: "109,99",
            pricenow: "98,99",
            description: "Cabo Enrolado AVIATOR - Modelo Black e Pink",
            link: "keyboard-cable-aviator-black",
            discount: "-10%",
            class: "cable-aviator"
        },
        {
            id: 48,
            name: "cabo-teclado",
            image: require("../images/produtos/cabo-sakura.png"),
            title: "CABO PARA TECLADO",
            price: "109,99",
            pricenow: "98,99",
            description: "Cabo Enrolado AVIATOR - Modelo Sakura",
            link: "keyboard-cable-aviator-sakura",
            discount: "-10%",
            class: "cable-aviator"
        },
        {
            id: 49,
            name: "cabo-teclado",
            image: require("../images/produtos/cabo-macaw.png"),
            title: "CABO PARA TECLADO",
            price: "109,99",
            pricenow: "98,99",
            description: "Cabo Enrolado AVIATOR - Modelo Macaw",
            link: "keyboard-cable-aviator-macaw",
            discount: "-10%",
            class: "cable-aviator"
        },
        {
            id: 50,
            name: "cabo-teclado",
            image: require("../images/produtos/cabo-los-angeles.png"),
            title: "CABO PARA TECLADO",
            price: "109,99",
            pricenow: "98,99",
            description: "Cabo Enrolado AVIATOR - Modelo Los Angeles",
            link: "keyboard-cable-aviator-los-angeles",
            discount: "-10%",
            class: "cable-aviator"
        },
        {
            id: 51,
            name: "headsets",
            image: require("../images/produtos/headset-diomedes.png"),
            title: "HEADSET GAMER",
            price: "269,99",
            pricenow: "234,99",
            description: "Headset Redragon Diomedes Preto",
            link: "headset-diomedes",
            discount: "-12%",
            class: "headset"
        },
        {
            id: 52,
            name: "headsets",
            image: require("../images/produtos/headset-cadmus.png"),
            title: "HEADSET GAMER",
            price: "259,99",
            pricenow: "229,99",
            description: "Headset Redragon Cadmus RGB",
            link: "headset-cadmus",
            discount: "-11%",
            class: "headset"
        },
        {
            id: 53,
            name: "headsets",
            image: require("../images/produtos/headset-scylla-branco.webp"),
            title: "HEADSET GAMER",
            price: "169,99",
            pricenow: "129,99",
            description: "Headset Scylla Branco H210",
            link: "headset-scylla-branco",
            discount: "-20%",
            class: "headset"
        },
        {
            id: 54,
            name: "gabinetes",
            image: require("../images/produtos/gabinete-p03.png"),
            title: "GABINETE GAMER",
            price: "219,99",
            pricenow: "189,99",
            description: "Gabinete T-DAGGER TGC-P03 Branco",
            link: "gabinete-gamer-p03",
            discount: "-13%",
            class: "gabinete"
        },
        {
            id: 55,
            name: "mouses",
            image: require("../images/produtos/mouse-storm-preto.png"),
            title: "MOUSE GAMER",
            price: "269,99",
            pricenow: "239,99",
            description: "Mouse Redragon Storm Pro Wireless Preto",
            link: "mouse-storm-pro-wireless",
            discount: "-11%",
            class: "mouses"
        },
        {
            id: 56,
            name: "teclados",
            image: require("../images/produtos/teclado-draconic.png"),
            title: "TECLADO MECÂNICO REDRAGON",
            price: "379,99",
            pricenow: "349,99",
            description: "Teclado Redragon Draconic Pro Branco e Rosa ",
            link: "teclado-redragon-draonic-pro",
            discount: "-7%",
            class: "teclado-draonic"
        },
        {
            id: 57,
            name: "teclados",
            image: require("../images/produtos/teclado-anivia.png"),
            title: "TECLADO MECÂNICO REDRAGON",
            price: "279,99",
            pricenow: "249,99",
            description: "Teclado Redragon Anivia Low Profile RGB ",
            link: "teclado-redragon-anivia",
            discount: "-10%",
            class: "teclado-gamdias"
        },
        {
            id: 58,
            name: "teclados",
            image: require("../images/produtos/teclado-optico.png"),
            title: "TECLADO GAMER ÓPTICO",
            price: "349,99",
            pricenow: "324,99",
            description: "Teclado Óptico Magic-Wand Branco - Pro RGB",
            link: "teclado-redragon-optico",
            discount: "-7%",
            class: "teclado-optic"
        },
        {
            id: 59,
            name: "switches",
            image: require("../images/produtos/switch-lavander.png"),
            title: "KIT SWITCH AKKO LAVANDER PURPLE",
            price: "89,99",
            pricenow: "71,99",
            description: "Switch Para Teclado Mecânico Akko.",
            link: "switch-akko-lavander",
            discount: "-20%",
            class: "switches"
        },
        {
            id: 60,
            name: "headsets",
            image: require("../images/produtos/hero-branco-roxo.webp"),
            title: "HEADSET GAMER",
            price: "239,99",
            pricenow: "204,99",
            description: "Headset Hero Branco com Roxo H530-WP",
            link: "headset-hero-branco-roxo",
            discount: "-14%",
            class: "headset-hero"
        },
        {
            id: 61,
            name: "teclados",
            image: require("../images/produtos/teclado-lakshmi.png"),
            title: "TECLADO MECÂNICO REDRAGON",
            price: "249,99",
            pricenow: "218,99",
            description: "Teclado Redragon Lakshmi 60% - Branco e Rosa",
            link: "teclado-redragon-lakshmi",
            discount: "-12%",
            class: "teclado-lakshmi"
        },
        {
            id: 62,
            name: "headsets",
            image: require("../images/produtos/headset-minos-branco.webp"),
            title: "HEADSET GAMER",
            price: "219,99",
            pricenow: "184,99",
            description: "Headset Minos Branco H210W",
            link: "headset-minos-branco",
            discount: "-16%",
            class: "headset"
        }
    ],
};
export default data